### ISSUE TITLE
mac install is err

### ISSUE THREAD

**Issue by IseEkko** [go-zing/gozz#1]
╰─ go install github.com/go-zing/gozz@latest           
# github.com/go-zing/gozz
ld: warning: -bind_at_load is deprecated on macOS
ld: warning: '/private/var/folders/55/2cf9m54s36q_1yf2j1svkf580000gn/T/go-link-48884605/go.o' has malformed LC_DYSYMTAB, expected 116 undefined symbols to start at index 29448, found 129 undefined symbols starting at index 66

**Comment by Just-maple** [comment]
Welcome to open first issue in this repo.

> If you see lines starting with ld: warning but not other outputs, they are just warnings, not errors. You should still get a binary, if there is no other output. Please only report if you see a link error, or a broken binary, or a warning that is not mentioned in the "warnings" section below. Thanks.


Your problem may caused by Xcode compatibility. Here is another similar case.[#61229](https://github.com/golang/go/issues/61229)

You could try reinstall another version of  Xcode or a compatible Golang
